title:            John <em>A</em> <strong>De Goes</strong>
text_title:       John A De Goes
tagline:          ramblings of a geek
description:      The home on the web for technologist John A. De Goes.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              

# Owner/author information
owner:
  name:           John A De Goes
  avatar:         http://www.gravatar.com/avatar/6fbccc0537949767c52dfc210003ec9d.jpg?s=200&r=g&d=identicon
  bio:            "I love startups, technology, and science. I write about geeky stuff. Mostly."
  email:          john@degoes.net
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        http://twitter.com/jdegoes
  facebook:       
  github:         http://github.com/jdegoes
  linkedin:       http://linkedin.com/in/jdegoes
  instagram:      
  lastfm:         
  tumblr:         
  disqus:         johnadegoes
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

excerpt_separator: yabber jabber wibber wabber

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Talks
    url: /talks/
  - title: Photos
    url: /photos/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]